
pipeline {
    agent any

    environment {
        VENV = "venv"
        ImageName = "dockerhub_username/messaging_app"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git credentialsId: 'github-creds',
                    url: 'https://github.com/AyoubArdem/alx-backend-python.git',
                    branch: 'main'
            }
        }
       

        stage('run dependencies') {
            steps {
               sh '''
               python3 -m virtualenv 
               virualenv $VENV
               . $VENV/bin/Activate
               pip install -r requirments.txt
               '''
            }
        }
         

        stage('Run Tests') {
            steps {
                sh '''
                . $VENV/bin/activate
                pytest --junitxml=test-results.xml
                '''
            }
        }
   
      stage('build image'){
          steps{
              sh ' docker build -t  $ImageName .'
          }
      }
      stage('push docker image'){
          steps{
              
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )])
                sh '''
                    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                    docker push $IMAGE_NAME:latest
                    '''
          }
      
    post {
        always {
            junit 'test-results.xml'
        }
    }
}


